apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webapps.demoapp.devops.lk
spec:
  group: demoapp.devops.lk
  names:
    kind: WebApp
    listKind: WebAppList
    plural: webapps
    singular: webapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WebApp is the Schema for the webapps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WebAppSpec defines the desired state of WebApp
          properties:
            image:
              description: Image is the WebApp image from a custom repository
              type: string
            size:
              format: int32
              type: integer
          required:
          - image
          - size
          type: object
        status:
          description: WebAppStatus defines the observed state of WebApp
          properties:
            instances:
              description: Instances are the names of the WebApp pods
              items:
                type: string
              type: array
          required:
          - instances
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
